model_name: fine_tuned_m_r_cnn_1_2

tasks: ['bbox', 'segm']
heads: 
  bbox: 'fastrcnn'
  segm: 'maskrcnn'
  class:


device: cuda
distributed_training: False

num_classes: 2
hidden_layer_segm: 256

loss_fn:

dataset: pennpudanped
train_ds: /data/user/DATA_SSD1/__adri/PennFudanPed
val_ds: /data/user/DATA_SSD1/__adri/PennFudanPed
weights_path: /coding_linux20/encov_torch/nn_training/src/nn/weights/

batch_size: 4
epochs: 30
patience: 3
checkpoint_frequency: 10

train_steps:
val_steps: