model_name: fine_tuned_m_r_cnn_0

tasks: ['bbox', 'segm']
heads: 
  bbox: 'fastrcnn'
  segm: 'maskrcnn'
  class:


device: cuda
distributed_training: True

num_classes: 2
hidden_layer_segm: 256

loss_fn:

dataset: endovis
train_ds: /data/user/DATA_SSD/__adri/endovis/Test
val_ds: /data/user/DATA_SSD/__adri/endovis/Test
weights_path: /coding_linux20/encov_torch/nn_training/src/nn/weights/

batch_size: 6
epochs: 12
patience: 3
checkpoint_frequency: 3

train_steps: 2
val_steps: 1