model_name: fine_tuned_m_r_cnn

tasks: ['bbox', 'segm']
heads: 
  bbox: 'fastrcnn'
  segm: 'maskrcnn'
  class:


device: cuda
distributed_training: False

num_classes: 2
hidden_layer_segm: 256

loss_fn:

dataset: pennpudanped
train_ds: /coding_linux20/programming/python_scripts/encov_torch/nn_training/inp/PennFudanPed
val_ds: /coding_linux20/programming/python_scripts/encov_torch/nn_training/inp/PennFudanPed
weights_path: /coding_linux20/programming/python_scripts/encov_torch/nn_training/src/nn/weights/

batch_size: 2
epochs: 2
patience: 3
checkpoint_frequency:

train_steps: 2
val_steps: 1